### ISSUE TITLE
[BUG]: YawStep on AutoCrystal crashes game

### ISSUE THREAD

**Issue by xgraza** [momentumdevelopment/cosmos#28]
It's a super, super, super long stacktrace. Plus there's a lot of exceptions being thrown all in the logs. Here is the log file:
[latest.log](https://github.com/linustouchtips/cosmos/files/7333837/latest.log)

It's more towards the bottom. I assume its the YawStep doing it considering it's throwing in `cope.cosmos.client.features.modules.combat.AutoCrystal.onPacketSend(AutoCrystal.java:453)` and it was not doing this when the YawStep value was at 1 (or whatever the default was).

There's also a rendering bug, where if you have any HUD options on AutoCrystal enabled, the rest of the HUD will not render (arraylist, watermark, armor, etc). It also sometimes would basically flashbang me. Not kidding, the whole screen would turn white and the only way to fix it is to open the GUI and then it would happen like a minute after "fixing" it.

This is also after building it from source, so I'm aware I'm on an unstable version of Cosmos, but y'know.

**Comment by Sxmurai** [comment]
https://github.com/linustouchtips/cosmos/blob/main/src/main/java/cope/cosmos/client/features/modules/combat/AutoCrystal.java#L453

From what I can see, it's because you are sending a CPacketPlayer packet, which will then just recursively be called, if you see what I mean. As a CPacketPlayer packet is being sent in a listener specifically made to listen for CPacketPlayer packets. And since its using the Rotation packets, the `rotating` flag would be true. I think that might be why, I could be completely wrong but that's just my guess.

Speaking of rotations, the client has issues with you being able to move around while rotating. Eg. While attacking someone using Aura, or it would randomly TP me back to the position I was in a few 100ish ticks ago (I'm guessing) while using AutoCrystal.

**Comment by linustouchtips** [comment]
there is an issue with the sequential timing in aura, doesn't have to do with rotations. 

the method used for yawstep in the ca doesn't even work on strict servers regardless, so it needs a complete overhaul.

**Comment by linustouchtips** [comment]
the rotations that you visually see in pyro and future are just cosmetic and don't actually affect the rotations. the rotations are modified through packets and the body movement is just a render for the player to better visualize the rotation.
